//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaServicio.srAuthors {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srAuthors.wsAuthorsSoap")]
    public interface wsAuthorsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Agregar(string Codigo, string Nombre, string Apellidos, string Telefono, string Direccion, string Ciudad, string Estado, string Zip, int Contrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> AgregarAsync(string Codigo, string Nombre, string Apellidos, string Telefono, string Direccion, string Ciudad, string Estado, string Zip, int Contrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Actualizar(string Codigo, string Nombre, string Apellidos, string Telefono, string Direccion, string Ciudad, string Estado, string Zip, int Contrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ActualizarAsync(string Codigo, string Nombre, string Apellidos, string Telefono, string Direccion, string Ciudad, string Estado, string Zip, int Contrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsAuthorsSoapChannel : CapaServicio.srAuthors.wsAuthorsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsAuthorsSoapClient : System.ServiceModel.ClientBase<CapaServicio.srAuthors.wsAuthorsSoap>, CapaServicio.srAuthors.wsAuthorsSoap {
        
        public wsAuthorsSoapClient() {
        }
        
        public wsAuthorsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsAuthorsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAuthorsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAuthorsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string[] Agregar(string Codigo, string Nombre, string Apellidos, string Telefono, string Direccion, string Ciudad, string Estado, string Zip, int Contrato) {
            return base.Channel.Agregar(Codigo, Nombre, Apellidos, Telefono, Direccion, Ciudad, Estado, Zip, Contrato);
        }
        
        public System.Threading.Tasks.Task<string[]> AgregarAsync(string Codigo, string Nombre, string Apellidos, string Telefono, string Direccion, string Ciudad, string Estado, string Zip, int Contrato) {
            return base.Channel.AgregarAsync(Codigo, Nombre, Apellidos, Telefono, Direccion, Ciudad, Estado, Zip, Contrato);
        }
        
        public string[] Actualizar(string Codigo, string Nombre, string Apellidos, string Telefono, string Direccion, string Ciudad, string Estado, string Zip, int Contrato) {
            return base.Channel.Actualizar(Codigo, Nombre, Apellidos, Telefono, Direccion, Ciudad, Estado, Zip, Contrato);
        }
        
        public System.Threading.Tasks.Task<string[]> ActualizarAsync(string Codigo, string Nombre, string Apellidos, string Telefono, string Direccion, string Ciudad, string Estado, string Zip, int Contrato) {
            return base.Channel.ActualizarAsync(Codigo, Nombre, Apellidos, Telefono, Direccion, Ciudad, Estado, Zip, Contrato);
        }
        
        public System.Data.DataSet Buscar(string texto, string criterio) {
            return base.Channel.Buscar(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio) {
            return base.Channel.BuscarAsync(texto, criterio);
        }
    }
}
